var annotated_dup =
[
    [ "detail", "namespacedetail.html", [
      [ "dragonbox", "namespacedetail_1_1dragonbox.html", [
        [ "decimal_fp", "structdetail_1_1dragonbox_1_1decimal__fp.html", "structdetail_1_1dragonbox_1_1decimal__fp" ],
        [ "float_info", "structdetail_1_1dragonbox_1_1float__info.html", null ],
        [ "float_info< double >", "structdetail_1_1dragonbox_1_1float__info_3_01double_01_4.html", "structdetail_1_1dragonbox_1_1float__info_3_01double_01_4" ],
        [ "float_info< float >", "structdetail_1_1dragonbox_1_1float__info_3_01float_01_4.html", "structdetail_1_1dragonbox_1_1float__info_3_01float_01_4" ],
        [ "float_info< T, enable_if_t< is_double_double< T >::value > >", "structdetail_1_1dragonbox_1_1float__info_3_01T_00_01enable__if__t_3_01is__double__double_3_01T_01_4_1_1value_01_4_01_4.html", "structdetail_1_1dragonbox_1_1float__info_3_01T_00_01enable__if__t_3_01is__double__double_3_01T_01_4_1_1value_01_4_01_4" ],
        [ "float_info< T, enable_if_t< std::numeric_limits< T >::digits==64||std::numeric_limits< T >::digits==113||is_float128< T >::value > >", "structdetail_1_1dragonbox_1_1float__info_3_01T_00_01enable__if__t_3_01std_1_1numeric__limits_3_099b10ab0a2f942de1fd73a3e930eb71c.html", "structdetail_1_1dragonbox_1_1float__info_3_01T_00_01enable__if__t_3_01std_1_1numeric__limits_3_099b10ab0a2f942de1fd73a3e930eb71c" ]
      ] ],
      [ "allocator", "structdetail_1_1allocator.html", "structdetail_1_1allocator" ],
      [ "arg_formatter", "structdetail_1_1arg__formatter.html", "structdetail_1_1arg__formatter" ],
      [ "arg_pack", "structdetail_1_1arg__pack.html", null ],
      [ "arg_ref", "uniondetail_1_1arg__ref.html", "uniondetail_1_1arg__ref" ],
      [ "basic_fp", "structdetail_1_1basic__fp.html", "structdetail_1_1basic__fp" ],
      [ "big_decimal_fp", "structdetail_1_1big__decimal__fp.html", "structdetail_1_1big__decimal__fp" ],
      [ "bigint", "classdetail_1_1bigint.html", "classdetail_1_1bigint" ],
      [ "buffer", "classdetail_1_1buffer.html", "classdetail_1_1buffer" ],
      [ "buffer_traits", "structdetail_1_1buffer__traits.html", "structdetail_1_1buffer__traits" ],
      [ "compile_parse_context", "classdetail_1_1compile__parse__context.html", "classdetail_1_1compile__parse__context" ],
      [ "compile_string", "structdetail_1_1compile__string.html", null ],
      [ "container_buffer", "classdetail_1_1container__buffer.html", "classdetail_1_1container__buffer" ],
      [ "counting_buffer", "classdetail_1_1counting__buffer.html", "classdetail_1_1counting__buffer" ],
      [ "custom_tag", "structdetail_1_1custom__tag.html", null ],
      [ "custom_value", "structdetail_1_1custom__value.html", "structdetail_1_1custom__value" ],
      [ "default_arg_formatter", "structdetail_1_1default__arg__formatter.html", "structdetail_1_1default__arg__formatter" ],
      [ "digit_grouping", "classdetail_1_1digit__grouping.html", "classdetail_1_1digit__grouping" ],
      [ "dynamic_format_specs", "structdetail_1_1dynamic__format__specs.html", "structdetail_1_1dynamic__format__specs" ],
      [ "dynamic_spec_getter", "structdetail_1_1dynamic__spec__getter.html", "structdetail_1_1dynamic__spec__getter" ],
      [ "dynamic_spec_handler", "structdetail_1_1dynamic__spec__handler.html", "structdetail_1_1dynamic__spec__handler" ],
      [ "fallback_digit_grouping", "classdetail_1_1fallback__digit__grouping.html", "classdetail_1_1fallback__digit__grouping" ],
      [ "find_escape_result", "structdetail_1_1find__escape__result.html", "structdetail_1_1find__escape__result" ],
      [ "fixed_buffer_traits", "classdetail_1_1fixed__buffer__traits.html", "classdetail_1_1fixed__buffer__traits" ],
      [ "fixed_string", "structdetail_1_1fixed__string.html", "structdetail_1_1fixed__string" ],
      [ "float128", "structdetail_1_1float128.html", null ],
      [ "format_arg_store", "structdetail_1_1format__arg__store.html", "structdetail_1_1format__arg__store" ],
      [ "format_handler", "structdetail_1_1format__handler.html", "structdetail_1_1format__handler" ],
      [ "format_string_checker", "classdetail_1_1format__string__checker.html", "classdetail_1_1format__string__checker" ],
      [ "has_append", "structdetail_1_1has__append.html", null ],
      [ "has_append< OutputIt, InputIt, void_t< decltype(get_container(std::declval< OutputIt >()) .append(std::declval< InputIt >(), std::declval< InputIt >()))> >", "structdetail_1_1has__append_3_01OutputIt_00_01InputIt_00_01void__t_3_01decltype_07get__container63d1792777df424daf0ec642040a8751.html", null ],
      [ "has_insert", "structdetail_1_1has__insert.html", null ],
      [ "has_insert< OutputIt, T, void_t< decltype(get_container(std::declval< OutputIt >()) .insert({}, std::declval< T >(), std::declval< T >()))> >", "structdetail_1_1has__insert_3_01OutputIt_00_01T_00_01void__t_3_01decltype_07get__container_07stdb299ca0128562c4d616cdf34818b4b7f.html", null ],
      [ "has_isfinite", "structdetail_1_1has__isfinite.html", null ],
      [ "has_isfinite< T, enable_if_t< sizeof(std::isfinite(T())) !=0 > >", "structdetail_1_1has__isfinite_3_01T_00_01enable__if__t_3_01sizeof_07std_1_1isfinite_07T_07_08_08_08_01_9_0a0_01_4_01_4.html", null ],
      [ "has_to_string_view", "structdetail_1_1has__to__string__view.html", null ],
      [ "has_to_string_view< T, void_t< decltype(detail::to_string_view(std::declval< T >()))> >", "structdetail_1_1has__to__string__view_3_01T_00_01void__t_3_01decltype_07detail_1_1to__string__via2b2866f7fc9fb7752b163dce36cc145.html", null ],
      [ "is_back_insert_iterator", "structdetail_1_1is__back__insert__iterator.html", null ],
      [ "is_back_insert_iterator< basic_appender< T > >", "structdetail_1_1is__back__insert__iterator_3_01basic__appender_3_01T_01_4_01_4.html", null ],
      [ "is_back_insert_iterator< It, bool_constant< std::is_same< decltype(adl::invoke_back_inserter< typename It::container_type >()), It >::value > >", "structdetail_1_1is__back__insert__iterator_3_01It_00_01bool__constant_3_01std_1_1is__same_3_01de2e5d6fff63151d2f6c9d619c9ef6d40a.html", null ],
      [ "is_buffer_appender", "structdetail_1_1is__buffer__appender.html", null ],
      [ "is_buffer_appender< It, bool_constant< is_back_insert_iterator< It >::value &&std::is_base_of< buffer< typename It::container_type::value_type >, typename It::container_type >::value > >", "structdetail_1_1is__buffer__appender_3_01It_00_01bool__constant_3_01is__back__insert__iterator_31014ad756ec92630ad9dc2a85ea12ced.html", null ],
      [ "is_code_unit", "structdetail_1_1is__code__unit.html", null ],
      [ "is_code_unit< char >", "structdetail_1_1is__code__unit_3_01char_01_4.html", null ],
      [ "is_code_unit< char16_t >", "structdetail_1_1is__code__unit_3_01char16__t_01_4.html", null ],
      [ "is_code_unit< char32_t >", "structdetail_1_1is__code__unit_3_01char32__t_01_4.html", null ],
      [ "is_code_unit< wchar_t >", "structdetail_1_1is__code__unit_3_01wchar__t_01_4.html", null ],
      [ "is_floating_point", "structdetail_1_1is__floating__point.html", null ],
      [ "is_floating_point< float128 >", "structdetail_1_1is__floating__point_3_01float128_01_4.html", null ],
      [ "is_integral", "structdetail_1_1is__integral.html", null ],
      [ "is_integral< native_int128 >", "structdetail_1_1is__integral_3_01native__int128_01_4.html", null ],
      [ "is_integral< uint128_t >", "structdetail_1_1is__integral_3_01uint128__t_01_4.html", null ],
      [ "is_named_arg", "structdetail_1_1is__named__arg.html", null ],
      [ "is_named_arg< named_arg< T, Char > >", "structdetail_1_1is__named__arg_3_01named__arg_3_01T_00_01Char_01_4_01_4.html", null ],
      [ "is_output_iterator", "structdetail_1_1is__output__iterator.html", null ],
      [ "is_output_iterator< appender, char >", "structdetail_1_1is__output__iterator_3_01appender_00_01char_01_4.html", null ],
      [ "is_output_iterator< It, T, enable_if_t< std::is_assignable< decltype(*std::declval< decay_t< It > & >()++), T >::value > >", "structdetail_1_1is__output__iterator_3_01It_00_01T_00_01enable__if__t_3_01std_1_1is__assignable_5c8307534b0459aed9468469f4222b36.html", null ],
      [ "is_static_named_arg", "structdetail_1_1is__static__named__arg.html", null ],
      [ "is_std_string_like", "structdetail_1_1is__std__string__like.html", null ],
      [ "is_std_string_like< T, void_t< decltype(std::declval< T >().find_first_of(typename T::value_type(), 0))> >", "structdetail_1_1is__std__string__like_3_01T_00_01void__t_3_01decltype_07std_1_1declval_3_01T_01_60c932241cfbc27891d3e7ecbb267cac.html", null ],
      [ "is_view", "structdetail_1_1is__view.html", null ],
      [ "is_view< T, bool_constant< sizeof(T) !=0 > >", "structdetail_1_1is__view_3_01T_00_01bool__constant_3_01sizeof_07T_08_01_9_0a0_01_4_01_4.html", null ],
      [ "iterator_buffer", "classdetail_1_1iterator__buffer.html", "classdetail_1_1iterator__buffer" ],
      [ "iterator_buffer< OutputIt, enable_if_t< is_back_insert_iterator< OutputIt >::value &&is_contiguous< typename OutputIt::container_type >::value, typename OutputIt::container_type::value_type > >", "classdetail_1_1iterator__buffer_3_01OutputIt_00_01enable__if__t_3_01is__back__insert__iterator_3dbcdfc8aa7bc335c93517ca2df4baab3.html", "classdetail_1_1iterator__buffer_3_01OutputIt_00_01enable__if__t_3_01is__back__insert__iterator_3dbcdfc8aa7bc335c93517ca2df4baab3" ],
      [ "iterator_buffer< T *, T >", "classdetail_1_1iterator__buffer_3_01T_01_5_00_01T_01_4.html", "classdetail_1_1iterator__buffer_3_01T_01_5_00_01T_01_4" ],
      [ "iterator_buffer< T *, T, fixed_buffer_traits >", "classdetail_1_1iterator__buffer_3_01T_01_5_00_01T_00_01fixed__buffer__traits_01_4.html", "classdetail_1_1iterator__buffer_3_01T_01_5_00_01T_00_01fixed__buffer__traits_01_4" ],
      [ "loc_writer", "structdetail_1_1loc__writer.html", "structdetail_1_1loc__writer" ],
      [ "named_arg", "structdetail_1_1named__arg.html", "structdetail_1_1named__arg" ],
      [ "named_arg_info", "structdetail_1_1named__arg__info.html", "structdetail_1_1named__arg__info" ],
      [ "named_arg_store", "structdetail_1_1named__arg__store.html", "structdetail_1_1named__arg__store" ],
      [ "named_arg_value", "structdetail_1_1named__arg__value.html", "structdetail_1_1named__arg__value" ],
      [ "native_formatter", "structdetail_1_1native__formatter.html", "structdetail_1_1native__formatter" ],
      [ "parse_dynamic_spec_result", "structdetail_1_1parse__dynamic__spec__result.html", "structdetail_1_1parse__dynamic__spec__result" ],
      [ "size_padding", "structdetail_1_1size__padding.html", "structdetail_1_1size__padding" ],
      [ "std_string_view", "structdetail_1_1std__string__view.html", "structdetail_1_1std__string__view" ],
      [ "string_literal", "structdetail_1_1string__literal.html", "structdetail_1_1string__literal" ],
      [ "string_value", "structdetail_1_1string__value.html", "structdetail_1_1string__value" ],
      [ "thousands_sep_result", "structdetail_1_1thousands__sep__result.html", "structdetail_1_1thousands__sep__result" ],
      [ "to_utf8", "classdetail_1_1to__utf8.html", "classdetail_1_1to__utf8" ],
      [ "type_constant", "structdetail_1_1type__constant.html", null ],
      [ "type_is_unformattable_for", "structdetail_1_1type__is__unformattable__for.html", null ],
      [ "type_mapper", "structdetail_1_1type__mapper.html", "structdetail_1_1type__mapper" ],
      [ "udl_arg", "structdetail_1_1udl__arg.html", "structdetail_1_1udl__arg" ],
      [ "uint128", "classdetail_1_1uint128.html", "classdetail_1_1uint128" ],
      [ "use_format_as", "structdetail_1_1use__format__as.html", null ],
      [ "use_format_as< T, bool_constant< std::is_arithmetic< format_as_result< T > >::value > >", "structdetail_1_1use__format__as_3_01T_00_01bool__constant_3_01std_1_1is__arithmetic_3_01format__439c79fefc40144049092c6814d868bd.html", null ],
      [ "use_format_as_member", "structdetail_1_1use__format__as__member.html", null ],
      [ "use_format_as_member< T, bool_constant< std::is_arithmetic< format_as_member_result< T > >::value > >", "structdetail_1_1use__format__as__member_3_01T_00_01bool__constant_3_01std_1_1is__arithmetic_3_01d9c483d23c56ebeb3084e53206817470.html", null ],
      [ "utf8_to_utf16", "classdetail_1_1utf8__to__utf16.html", "classdetail_1_1utf8__to__utf16" ],
      [ "value", "classdetail_1_1value.html", "classdetail_1_1value" ],
      [ "view", "structdetail_1_1view.html", null ],
      [ "write_int_arg", "structdetail_1_1write__int__arg.html", "structdetail_1_1write__int__arg" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "iterator_traits< fmt::basic_appender< T > >", "structstd_1_1iterator__traits_3_01fmt_1_1basic__appender_3_01T_01_4_01_4.html", "structstd_1_1iterator__traits_3_01fmt_1_1basic__appender_3_01T_01_4_01_4" ]
    ] ],
    [ "tengine", "namespacetengine.html", [
      [ "util", "namespacetengine_1_1util.html", [
        [ "cfg", "namespacetengine_1_1util_1_1cfg.html", [
          [ "CFGNode", "structtengine_1_1util_1_1cfg_1_1CFGNode.html", "structtengine_1_1util_1_1cfg_1_1CFGNode" ]
        ] ],
        [ "logger", "namespacetengine_1_1util_1_1logger.html", [
          [ "FileSink", "classtengine_1_1util_1_1logger_1_1FileSink.html", "classtengine_1_1util_1_1logger_1_1FileSink" ],
          [ "ILogSink", "classtengine_1_1util_1_1logger_1_1ILogSink.html", "classtengine_1_1util_1_1logger_1_1ILogSink" ],
          [ "LogFilter", "structtengine_1_1util_1_1logger_1_1LogFilter.html", "structtengine_1_1util_1_1logger_1_1LogFilter" ],
          [ "Logger", "classtengine_1_1util_1_1logger_1_1Logger.html", "classtengine_1_1util_1_1logger_1_1Logger" ],
          [ "TerminalSink", "classtengine_1_1util_1_1logger_1_1TerminalSink.html", "classtengine_1_1util_1_1logger_1_1TerminalSink" ]
        ] ]
      ] ]
    ] ],
    [ "basic_appender", "classbasic__appender.html", "classbasic__appender" ],
    [ "basic_format_arg", "classbasic__format__arg.html", "classbasic__format__arg" ],
    [ "basic_format_args", "classbasic__format__args.html", "classbasic__format__args" ],
    [ "basic_memory_buffer", "classbasic__memory__buffer.html", "classbasic__memory__buffer" ],
    [ "basic_specs", "classbasic__specs.html", "classbasic__specs" ],
    [ "basic_string_view", "classbasic__string__view.html", "classbasic__string__view" ],
    [ "bytes", "structbytes.html", "structbytes" ],
    [ "CapturedLog", "structCapturedLog.html", "structCapturedLog" ],
    [ "context", "classcontext.html", "classcontext" ],
    [ "DummySink", "classDummySink.html", "classDummySink" ],
    [ "FileSinkTest", "classFileSinkTest.html", "classFileSinkTest" ],
    [ "format_facet", "classformat__facet.html", "classformat__facet" ],
    [ "format_int", "classformat__int.html", "classformat__int" ],
    [ "format_specs", "structformat__specs.html", "structformat__specs" ],
    [ "format_to_n_result", "structformat__to__n__result.html", "structformat__to__n__result" ],
    [ "format_to_result", "structformat__to__result.html", "structformat__to__result" ],
    [ "formatter", "structformatter.html", "structformatter" ],
    [ "formatter< bytes >", "structformatter_3_01bytes_01_4.html", "structformatter_3_01bytes_01_4" ],
    [ "formatter< Char[N], Char >", "structformatter_3_01Char_0fN_0e_00_01Char_01_4.html", null ],
    [ "formatter< detail::float128, Char >", "structformatter_3_01detail_1_1float128_00_01Char_01_4.html", null ],
    [ "formatter< group_digits_view< T > >", "structformatter_3_01group__digits__view_3_01T_01_4_01_4.html", "structformatter_3_01group__digits__view_3_01T_01_4_01_4" ],
    [ "formatter< nested_view< T, Char >, Char >", "structformatter_3_01nested__view_3_01T_00_01Char_01_4_00_01Char_01_4.html", "structformatter_3_01nested__view_3_01T_00_01Char_01_4_00_01Char_01_4" ],
    [ "formatter< std::basic_string< Char, Traits, Allocator >, Char >", "classformatter_3_01std_1_1basic__string_3_01Char_00_01Traits_00_01Allocator_01_4_00_01Char_01_4.html", null ],
    [ "formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >", "structformatter_3_01T_00_01Char_00_01enable__if__t_3_01detail_1_1type__constant_3_01T_00_01Char_67602321fdfe0eb9cff36125517f1a34.html", null ],
    [ "formatter< T, Char, void_t< detail::format_as_result< T > > >", "structformatter_3_01T_00_01Char_00_01void__t_3_01detail_1_1format__as__result_3_01T_01_4_01_4_01_4.html", "structformatter_3_01T_00_01Char_00_01void__t_3_01detail_1_1format__as__result_3_01T_01_4_01_4_01_4" ],
    [ "fstring", "structfstring.html", "structfstring" ],
    [ "generic_context", "classgeneric__context.html", "classgeneric__context" ],
    [ "group_digits_view", "structgroup__digits__view.html", "structgroup__digits__view" ],
    [ "is_contiguous", "structis__contiguous.html", null ],
    [ "is_contiguous< basic_memory_buffer< T, SIZE, Allocator > >", "structis__contiguous_3_01basic__memory__buffer_3_01T_00_01SIZE_00_01Allocator_01_4_01_4.html", null ],
    [ "is_contiguous< std::basic_string< Char, Traits, Allocator > >", "structis__contiguous_3_01std_1_1basic__string_3_01Char_00_01Traits_00_01Allocator_01_4_01_4.html", null ],
    [ "loc_value", "classloc__value.html", "classloc__value" ],
    [ "locale_ref", "classlocale__ref.html", "classlocale__ref" ],
    [ "locking", "structlocking.html", null ],
    [ "LoggerTests", "classLoggerTests.html", "classLoggerTests" ],
    [ "monostate", "structmonostate.html", "structmonostate" ],
    [ "nested_formatter", "structnested__formatter.html", "structnested__formatter" ],
    [ "nested_view", "structnested__view.html", "structnested__view" ],
    [ "parse_context", "classparse__context.html", "classparse__context" ],
    [ "runtime_format_string", "structruntime__format__string.html", "structruntime__format__string" ],
    [ "string_buffer", "classstring__buffer.html", "classstring__buffer" ],
    [ "writer", "classwriter.html", "classwriter" ]
];